name: Build WaterTracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore WaterTracker.csproj

    - name: Build
      run: dotnet build WaterTracker.csproj --no-restore --configuration Release

    - name: Publish application
      run: dotnet publish WaterTracker.csproj --configuration Release --output ./publish

    - name: Zip release files
      run: Compress-Archive -Path ./publish/* -DestinationPath ./WaterTracker.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: WaterTracker Release ${{ github.sha }}
        files: ./WaterTracker.zip
        generate_release_notes: true
