name: Build WaterTracker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore WaterTracker.csproj

    - name: Build
      run: dotnet build WaterTracker.csproj --no-restore --configuration Release

    - name: Output build result
      run: echo Build completed successfully!
